import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";

export interface OrderItem {
  id: string;
  product_name: string;
  product_image: string | null;
  quantity: number;
  price: number;
}

export interface Order {
  id: string;
  order_number: string;
  status: 'placed' | 'confirmed' | 'dispatched' | 'shipped' | 'delivered' | 'cancelled';
  total_amount: number;
  shipping_address: string | null;
  shipping_city: string | null;
  shipping_postal_code: string | null;
  shipping_phone: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
  items?: OrderItem[];
}

export const useOrders = () => {
  const { user } = useAuth();
  const [orders, setOrders] = useState<Order[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchOrders = async () => {
    if (!user) {
      setOrders([]);
      setIsLoading(false);
      return;
    }

    setIsLoading(true);
    setError(null);

    const { data: ordersData, error: ordersError } = await supabase
      .from('orders')
      .select(`
        *,
        order_items (*)
      `)
      .eq('user_id', user.id)
      .order('created_at', { ascending: false });

    if (ordersError) {
      setError(ordersError.message);
      setIsLoading(false);
      return;
    }

    const formattedOrders = ordersData.map(order => ({
      ...order,
      items: order.order_items,
    })) as Order[];

    setOrders(formattedOrders);
    setIsLoading(false);
  };

  useEffect(() => {
    fetchOrders();
  }, [user]);

  const createOrder = async (orderData: {
    total_amount: number;
    shipping_address: string;
    shipping_city: string;
    shipping_postal_code: string;
    shipping_phone: string;
    notes?: string;
    items: { product_name: string; product_image?: string; quantity: number; price: number; product_id?: string }[];
  }) => {
    if (!user) return { error: new Error('Not authenticated') };

    // Create order - order_number is generated by trigger, we pass a placeholder
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert([{
        user_id: user.id,
        total_amount: orderData.total_amount,
        shipping_address: orderData.shipping_address,
        shipping_city: orderData.shipping_city,
        shipping_postal_code: orderData.shipping_postal_code,
        shipping_phone: orderData.shipping_phone,
        notes: orderData.notes,
        order_number: 'TEMP', // Will be overwritten by trigger
      }])
      .select()
      .single();

    if (orderError) return { error: orderError };

    // Create order items
    const orderItems = orderData.items.map(item => ({
      order_id: order.id,
      product_name: item.product_name,
      product_image: item.product_image,
      quantity: item.quantity,
      price: item.price,
      product_id: item.product_id,
    }));

    const { error: itemsError } = await supabase
      .from('order_items')
      .insert(orderItems);

    if (itemsError) return { error: itemsError };

    await fetchOrders();
    return { data: order, error: null };
  };

  const getOrdersByStatus = (status: Order['status'] | 'active' | 'completed') => {
    if (status === 'active') {
      return orders.filter(o => ['placed', 'confirmed', 'dispatched', 'shipped'].includes(o.status));
    }
    if (status === 'completed') {
      return orders.filter(o => o.status === 'delivered');
    }
    return orders.filter(o => o.status === status);
  };

  return {
    orders,
    isLoading,
    error,
    fetchOrders,
    createOrder,
    getOrdersByStatus,
    activeOrders: getOrdersByStatus('active'),
    completedOrders: getOrdersByStatus('completed'),
    cancelledOrders: getOrdersByStatus('cancelled'),
  };
};
