import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ThumbsUp, ThumbsDown, Sparkles, Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

interface Summary {
  summary?: string | null;
  pros?: string[];
  cons?: string[];
  reviewCount?: number;
}

const ReviewSummary = ({ productId }: { productId: string }) => {
  const [data, setData] = useState<Summary | null>(null);
  const [loading, setLoading] = useState(false);
  const [open, setOpen] = useState(false);

  const generate = async () => {
    if (data) { setOpen(o => !o); return; }
    setLoading(true);
    setOpen(true);
    try {
      const { data: result, error } = await supabase.functions.invoke("ai-summarize-reviews", {
        body: { productId },
      });
      if (error) throw error;
      setData(result);
    } catch (e) {
      setData({ summary: "Could not generate summary right now." });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mb-6">
      <button
        onClick={generate}
        className="w-full sm:w-auto group flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-gold/10 to-amber-500/10 border border-gold/30 hover:border-gold/60 transition-all text-sm font-medium"
      >
        <Sparkles className="w-4 h-4 text-gold group-hover:rotate-12 transition-transform" />
        {loading ? "Analyzing reviews..." : data ? (open ? "Hide AI Summary" : "Show AI Summary") : "AI Review Summary"}
      </button>

      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            className="overflow-hidden"
          >
            <div className="mt-3 p-4 rounded-xl bg-card border border-border">
              {loading ? (
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Loader2 className="w-4 h-4 animate-spin" /> Reading customer feedback...
                </div>
              ) : data && (data.pros?.length || data.summary) ? (
                <>
                  {data.summary && (
                    <p className="text-sm mb-4 italic text-muted-foreground">"{data.summary}"</p>
                  )}
                  <div className="grid sm:grid-cols-2 gap-4">
                    {data.pros && data.pros.length > 0 && (
                      <div>
                        <p className="flex items-center gap-1.5 text-xs font-semibold text-emerald-600 dark:text-emerald-400 mb-2">
                          <ThumbsUp className="w-3.5 h-3.5" /> What customers love
                        </p>
                        <ul className="space-y-1.5">
                          {data.pros.map((p, i) => (
                            <li key={i} className="text-sm flex gap-2"><span className="text-emerald-500">+</span>{p}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                    {data.cons && data.cons.length > 0 && (
                      <div>
                        <p className="flex items-center gap-1.5 text-xs font-semibold text-orange-600 dark:text-orange-400 mb-2">
                          <ThumbsDown className="w-3.5 h-3.5" /> Things to consider
                        </p>
                        <ul className="space-y-1.5">
                          {data.cons.map((c, i) => (
                            <li key={i} className="text-sm flex gap-2"><span className="text-orange-500">−</span>{c}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                  {data.reviewCount !== undefined && (
                    <p className="text-xs text-muted-foreground mt-3 pt-3 border-t border-border">
                      Based on {data.reviewCount} customer reviews · Generated by AI
                    </p>
                  )}
                </>
              ) : (
                <p className="text-sm text-muted-foreground">
                  Not enough reviews yet to summarize. Be the first to share your experience!
                </p>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default ReviewSummary;
